fix: failed to load PostgreSQL database info
Error: failed to load PostgreSQL database info

Caused by:
    0: error occurred while decoding column database_name: error in Any driver mapping: Any driver does not support the Postgres type PgTypeInfo(Name)
    1: error in Any driver mapping: Any driver does not support the Postgres type PgTypeInfo(Name)
    2: Any driver does not support the Postgres type PgTypeInfo(Name)